### ISSUE TITLE
Create CSS files for each individual type of web page

### ISSUE THREAD

**Issue by Dodesimo** [theZFJ/zfjournal_source#11]
**DESCRIPTION** 
Now that test files have been created for our website, we need to create **custom CSS files** to customize the pages and help our website look appealing. 

**OBJECTIVE** 
Add custom CSS files to the theme in order to customize our webpages beyond the scope of the theme. 

**POSSIBLE SOLUTIONS** 
Steps to solving the problem:

1. Override ```head.html``` in our theme.
2. Create new ```head.html``` file.
3. Add path to ```config.toml```
4. Add path to new CSS stylesheet in **new** ```head.html```  file.
5. Create new CSS stylesheet in ```static``` folder (https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/d12129b88670e87e2bd0dbf4779ab00ffb6def13/static/css).
6. Edit CSS to match our needs and use ```hugo server -D``` to check such needs.

**REFERENCES**
For **steps 1 - 5**, check this link: https://www.banjocode.com/post/hugo/custom-css/.

**NOTE:** If none of this works, our best bet would be to ask the theme's **creator** or a **community** for the theme for assistance.

**Comment by akirarorschach** [comment]
The `head.html` file in the website_theme repo is at [https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/head/head.html](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/head/head.html). Here is the `prism.css` file that I have seen referenced in head.html: [https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/assets/css/prism.css](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/assets/css/prism.css). 

**One question:** are there any possible problems that may arise from having two `head.html` files? 

Also, let's get this issue **resolved by 2021-12-05**, next Sunday.

**Comment by Dodesimo** [comment]
I think it would be easier to just modify the existing ```head.html``` rather than making a new one. We should make a new issue for this since the problem has changed.
